### ISSUE TITLE
Open Links in app

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#1295]
Existing feature intending to open files/folders in app, by clicking a private link from outside.

Testing done over `feature/account-wizard` branch, commit `5a3745689`

**oC10:** no issues found. Links are correctly solved: app opened and item highlighted/opened by using `owncloud://` scheme

In **oCIS** links are not working. These are the steps i followed:

1. Get the privatelink. In my case, i got from  `PROPFIND` response:

```
    <d:propstat>
      <d:prop>
        ...
        <oc:privatelink>https://ocis.xxxx.owncloud.works/f/71135097-2849-442b-b3d8-7701539e8cf5$e90424c7-1bdb-4512-9e05-cba6b6ffbb74%21d7301af2-45f5-4a8d-b049-61946c042cd5</oc:privatelink>
        ...
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
```

2. In the app, add the account that contains the file
3. Create a link in any app/web to open it from outside the oC app
4. Click the link

Current: Link Resolution error, no matter where the item is stored: root, non-root, personal or custom space
Expected: Item highlighted

**Video and logs**

ID of the file open in the video: 
71135097-2849-442b-b3d8-7701539e8cf5$e90424c7-1bdb-4512-9e05-cba6b6ffbb74!a3b603fe-b1a8-490c-96a9-29a57d35021b

https://github.com/owncloud/ios-app/assets/14894746/bd24cdee-3317-47d8-aa9d-3a7d28487f7e

[ownCloud_14_Nov_2023_at_18_54_01.log.txt](https://github.com/owncloud/ios-app/files/13353624/ownCloud_14_Nov_2023_at_18_54_01.log.txt)

Testing over links feature will be led for the following test plan:
https://github.com/owncloud/QA/blob/ios/restructure_some_test_plans/Mobile/iOS/Feature%20template/Links/Open%20from%20Link.md

And new scenarios added to the proper feature file:
https://github.com/owncloud/ios-scenario-testing/blob/master/src/test/resources/io/cucumber/privatelink.feature

**Comment by michaelstingl** [comment]
For this link:
`owncloud://ocis.ocis-traefik.latest.owncloud.works/f/5e8c7cc9-e0a4-41c6-b50c-456c8b38a961$534bb038-6f9d-4093-946f-133be61fa4e7%218148e70c-f473-454f-beb3-43fde213383e`
HTTP requests and responses look good I'd say:

```
2023-11-14 21:39:28.699000+0100 ownCloud[91205:7934084] ⚪️ | [HTTP, Request, …] Sending request:
# REQUEST ---------------------------------------------------------
URL:         https://ocis.ocis-traefik.latest.owncloud.works/remote.php/dav/meta/5e8c7cc9-e0a4-41c6-b50c-456c8b38a961$534bb038-6f9d-4093-946f-133be61fa4e7!8148e70c-f473-454f-beb3-43fde213383e
Error:       -
Req Signals: authAvailable
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
PROPFIND /remote.php/dav/meta/5e8c7cc9-e0a4-41c6-b50c-456c8b38a961$534bb038-6f9d-4093-946f-133be61fa4e7!8148e70c-f473-454f-beb3-43fde213383e HTTP/1.1
Host: ocis.ocis-traefik.latest.owncloud.works
Content-Length: 159
Prefer: return=minimal
X-Request-ID: E5B333BB-C3C3-4DDB-B921-A1F69538B8C9
Original-Request-ID: E5B333BB-C3C3-4DDB-B921-A1F69538B8C9
Content-Type: application/xml
Depth: 0
User-Agent: ownCloudApp/12.0.3 (App/271; iOS/17.0.1; iPhone)
Authorization: Bearer [redacted:2]
Accept-Language: en

<?xml version="1.0" encoding="UTF-8"?>
<D:propfind xmlns:D="DAV:" xmlns:oc="http://owncloud.org/ns">
	<D:prop>
		<oc:meta-path-for-user/>
	</D:prop>
</D:propfind>

----------------------------------------------------------------- [… PROPFIND, RequestID:E5B333BB-C3C3-4DDB-B921-A1F69538B8C9, URLSessionTaskID:71] [OCHTTPPipeline.m:1184|FULL]
```

```
2023-11-14 21:39:28.747000+0100 ownCloud[91205:7934084] ⚪️ | [HTTP, Response, …] Received response:
# RESPONSE --------------------------------------------------------
Method:      PROPFIND
URL:         https://ocis.ocis-traefik.latest.owncloud.works/remote.php/dav/meta/5e8c7cc9-e0a4-41c6-b50c-456c8b38a961$534bb038-6f9d-4093-946f-133be61fa4e7!8148e70c-f473-454f-beb3-43fde213383e
Request-ID:  E5B333BB-C3C3-4DDB-B921-A1F69538B8C9
Error:       -
Req Signals: authAvailable
Metrics:     { total: [2023-11-14 20:39:28 +0000 - 2023-11-14 20:39:28 +0000, 0.05 sec], startedAfter: 0.00, redirects: 0, transactions: [1: fetchStart: 0.00, request: 0.00..0.01 (0.00), cloud: 0.01..0.04 (0.03), response: 0.04..0.04 (0.00)] }
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
207 SUCCESS
Access-Control-Allow-Origin: *
Content-Type: application/xml; charset=utf-8
content-security-policy: default-src 'none';
dav: 1, 3, extended-mkcol
x-download-options: noopen
x-xss-protection: 1; mode=block
x-permitted-cross-domain-policies: none
Date: Tue, 14 Nov 2023 20:39:28 GMT
x-request-id: E5B333BB-C3C3-4DDB-B921-A1F69538B8C9
x-robots-tag: none
Content-Length: 773
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
Vary: Origin

<d:multistatus xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:s="http://sabredav.org/ns">
	<d:response>
		<d:href>/remote.php/dav/meta/5e8c7cc9-e0a4-41c6-b50c-456c8b38a961$534bb038-6f9d-4093-946f-133be61fa4e7%218148e70c-f473-454f-beb3-43fde213383e/</d:href>
		<d:propstat>
			<d:prop>
				<oc:meta-path-for-user>/Test/Photo-2011-03-13-01-17-25_0001.JPG</oc:meta-path-for-user>
				<oc:id>5e8c7cc9-e0a4-41c6-b50c-456c8b38a961$534bb038-6f9d-4093-946f-133be61fa4e7!8148e70c-f473-454f-beb3-43fde213383e</oc:id>
				<oc:fileid>5e8c7cc9-e0a4-41c6-b50c-456c8b38a961$534bb038-6f9d-4093-946f-133be61fa4e7!8148e70c-f473-454f-beb3-43fde213383e</oc:fileid>
				<oc:spaceid>5e8c7cc9-e0a4-41c6-b50c-456c8b38a961</oc:spaceid>
			</d:prop>
			<d:status>HTTP/1.1 200 OK</d:status>
		</d:propstat>
	</d:response>
</d:multistatus>
----------------------------------------------------------------- [… PROPFIND, RequestID:E5B333BB-C3C3-4DDB-B921-A1F69538B8C9, URLSessionTaskID:71] [OCHTTPPipeline.m:1307|FULL]

```

**Comment by felix-schwarz** [comment]
I looked into it and so far `<oc:spaceid>` was not used, so that no correct location could be assembled.

I changed the code to use `<oc:spaceid>`, but then noticed that the driveID provided by it is incomplete, so that the resolution still fails in the end.

Here's an example, resolving `https://](https://ocis.ocis-wopi.latest.owncloud.works/f/71135097-2849-442b-b3d8-7701539e8cf5%24e90424c7-1bdb-4512-9e05-cba6b6ffbb74%2197b970f2-18dc-4e80-b154-cec25285b959`, which points to folder `/555/` in the personal space.

```
# REQUEST ---------------------------------------------------------
URL:         https://ocis.ocis-wopi.latest.owncloud.works/remote.php/dav/meta/71135097-2849-442b-b3d8-7701539e8cf5$e90424c7-1bdb-4512-9e05-cba6b6ffbb74!97b970f2-18dc-4e80-b154-cec25285b959
Error:       -
Req Signals: authAvailable
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
PROPFIND /remote.php/dav/meta/71135097-2849-442b-b3d8-7701539e8cf5$e90424c7-1bdb-4512-9e05-cba6b6ffbb74!97b970f2-18dc-4e80-b154-cec25285b959 HTTP/1.1
Host: ocis.ocis-wopi.latest.owncloud.works
Content-Length: 159
Prefer: return=minimal
X-Request-ID: 5364EEF1-0DDB-4886-BACD-3088459998D5
Original-Request-ID: 5364EEF1-0DDB-4886-BACD-3088459998D5
Content-Type: application/xml
Depth: 0
User-Agent: ownCloudApp/12.0.3 (App/271; iOS/17.0.1; iPhone)
Authorization: Bearer [redacted:3]
Accept-Language: en

<?xml version="1.0" encoding="UTF-8"?>
<D:propfind xmlns:D="DAV:" xmlns:oc="http://owncloud.org/ns">
<D:prop>
<oc:meta-path-for-user/>
</D:prop>
</D:propfind>

# RESPONSE --------------------------------------------------------
Method:      PROPFIND
URL:         https://ocis.ocis-wopi.latest.owncloud.works/remote.php/dav/meta/71135097-2849-442b-b3d8-7701539e8cf5$e90424c7-1bdb-4512-9e05-cba6b6ffbb74!97b970f2-18dc-4e80-b154-cec25285b959
Request-ID:  5364EEF1-0DDB-4886-BACD-3088459998D5
Error:       -
Req Signals: authAvailable
Metrics:     { total: [2023-11-14 23:08:10 +0000 - 2023-11-14 23:08:10 +0000, 0.16 sec], startedAfter: 0.00, redirects: 0, transactions: [1: fetchStart: 0.00, request: 0.00..0.00 (0.00), cloud: 0.00..0.15 (0.15), response: 0.15..0.15 (0.00)] }
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
207 SUCCESS
Access-Control-Allow-Origin: *
Content-Type: application/xml; charset=utf-8
content-security-policy: default-src 'none';
dav: 1, 3, extended-mkcol
x-download-options: noopen
x-xss-protection: 1; mode=block
x-permitted-cross-domain-policies: none
Date: Tue, 14 Nov 2023 23:08:10 GMT
x-request-id: 5364EEF1-0DDB-4886-BACD-3088459998D5
x-robots-tag: none
Content-Length: 737
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
Vary: Origin

<d:multistatus
	xmlns:s="http://sabredav.org/ns"
	xmlns:d="DAV:"
	xmlns:oc="http://owncloud.org/ns">
	<d:response>
		<d:href>/remote.php/dav/meta/71135097-2849-442b-b3d8-7701539e8cf5$e90424c7-1bdb-4512-9e05-cba6b6ffbb74%2197b970f2-18dc-4e80-b154-cec25285b959/</d:href>
		<d:propstat>
			<d:prop>
				<oc:meta-path-for-user>/555</oc:meta-path-for-user>
				<oc:id>71135097-2849-442b-b3d8-7701539e8cf5$e90424c7-1bdb-4512-9e05-cba6b6ffbb74!97b970f2-18dc-4e80-b154-cec25285b959</oc:id>
				<oc:fileid>71135097-2849-442b-b3d8-7701539e8cf5$e90424c7-1bdb-4512-9e05-cba6b6ffbb74!97b970f2-18dc-4e80-b154-cec25285b959</oc:fileid>
				<oc:spaceid>71135097-2849-442b-b3d8-7701539e8cf5</oc:spaceid>
			</d:prop>
			<d:status>HTTP/1.1 200 OK</d:status>
		</d:propstat>
	</d:response>
</d:multistatus>
```

The drive/space ID returned here is different from what the drive list returned earlier for the personal space:
- `71135097-2849-442b-b3d8-7701539e8cf5` (returned by meta endpoint)
- `71135097-2849-442b-b3d8-7701539e8cf5$e90424c7-1bdb-4512-9e05-cba6b6ffbb74` (returned by the drive list endpoint)

```
# RESPONSE --------------------------------------------------------
Method:      GET
URL:         https://ocis.ocis-wopi.latest.owncloud.works/graph/v1.0/me/drives
Request-ID:  D2AF9AAD-4BCA-41F4-9980-35D343B926CF
Error:       -
Req Signals: authAvailable
Metrics:     { total: [2023-11-14 23:02:35 +0000 - 2023-11-14 23:02:36 +0000, 0.64 sec], startedAfter: 0.00, redirects: 0, transactions: [1: fetchStart: 0.00, request: 0.00..0.00 (0.00), cloud: 0.00..0.63 (0.63), response: 0.63..0.63 (0.00)] }
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
200 NO ERROR
x-content-type-options: nosniff
Content-Type: application/json
content-security-policy: frame-ancestors 'none'
Date: Tue, 14 Nov 2023 23:02:36 GMT
x-frame-options: DENY
x-request-id: D2AF9AAD-4BCA-41F4-9980-35D343B926CF
x-graph-version: 5.0.0-alpha.2+552b87654
Vary: Origin

{
  "value": [
    {
      "driveAlias": "virtual/shares",
      "driveType": "virtual",
      "id": "a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668",
      "name": "Shares",
      "root": {
        "eTag": "DECAFC00FEE",
        "id": "a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668",
        "webDavUrl": "https://ocis.ocis-wopi.latest.owncloud.works/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668"
      },
      "webUrl": "https://ocis.ocis-wopi.latest.owncloud.works/f/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668"
    },
    {
      "driveAlias": "personal/admin",
      "driveType": "personal",
      "id": "71135097-2849-442b-b3d8-7701539e8cf5$e90424c7-1bdb-4512-9e05-cba6b6ffbb74",
      "lastModifiedDateTime": "2023-11-14T17:51:30.060115701Z",
      "name": "Admin",
      "owner": {
        "user": {
          "displayName": "",
          "id": "e90424c7-1bdb-4512-9e05-cba6b6ffbb74"
        }
      },
      "quota": {
        "remaining": 27148849152,
        "state": "normal",
        "total": 0,
        "used": 540925
      },
      "root": {
        "eTag": "\"a62df2dccd83d865246053818b1616de\"",
        "id": "71135097-2849-442b-b3d8-7701539e8cf5$e90424c7-1bdb-4512-9e05-cba6b6ffbb74",
        "webDavUrl": "https://ocis.ocis-wopi.latest.owncloud.works/dav/spaces/71135097-2849-442b-b3d8-7701539e8cf5$e90424c7-1bdb-4512-9e05-cba6b6ffbb74"
      },
      "webUrl": "https://ocis.ocis-wopi.latest.owncloud.works/f/71135097-2849-442b-b3d8-7701539e8cf5$e90424c7-1bdb-4512-9e05-cba6b6ffbb74"
    },
    {
      "driveAlias": "project/test-space",
      "driveType": "project",
      "id": "71135097-2849-442b-b3d8-7701539e8cf5$13e07352-d7e5-42e1-9a4d-2d926dfb4ec7",
      "lastModifiedDateTime": "2023-11-14T12:28:40.615466025Z",
      "name": "test space",
      "owner": {
        "user": {
          "displayName": "",
          "id": "13e07352-d7e5-42e1-9a4d-2d926dfb4ec7"
        }
      },
      "quota": {
        "remaining": 999999954,
        "state": "normal",
        "total": 1000000000,
        "used": 46
      },
      "root": {
        "eTag": "\"3c9ef1515aaa323eaf9489f39da1d96c\"",
        "id": "71135097-2849-442b-b3d8-7701539e8cf5$13e07352-d7e5-42e1-9a4d-2d926dfb4ec7",
        "permissions": [
          {
            "grantedToIdentities": [
              {
                "user": {
                  "displayName": "Admin",
                  "id": "e90424c7-1bdb-4512-9e05-cba6b6ffbb74"
                }
              }
            ],
            "roles": [
              "manager"
            ]
          }
        ],
        "webDavUrl": "https://ocis.ocis-wopi.latest.owncloud.works/dav/spaces/71135097-2849-442b-b3d8-7701539e8cf5$13e07352-d7e5-42e1-9a4d-2d926dfb4ec7"
      },
      "special": [
        {
          "eTag": "\"ddb6a24fcc117154565d3c1b239eb5b1\"",
          "file": {
            "mimeType": "text/markdown"
          },
          "id": "71135097-2849-442b-b3d8-7701539e8cf5$13e07352-d7e5-42e1-9a4d-2d926dfb4ec7!74942287-e186-4c09-9a57-c01bde822867",
          "lastModifiedDateTime": "2023-11-14T12:24:30.645807334Z",
          "name": "readme.md",
          "parentReference": {
            "driveId": "71135097-2849-442b-b3d8-7701539e8cf5$13e07352-d7e5-42e1-9a4d-2d926dfb4ec7",
            "driveType": "project",
            "id": "71135097-2849-442b-b3d8-7701539e8cf5$13e07352-d7e5-42e1-9a4d-2d926dfb4ec7!d933176a-c2d4-4827-9858-bc1948c81aac"
          },
          "size": 46,
          "specialFolder": {
            "name": "readme"
          },
          "webDavUrl": "https://ocis.ocis-wopi.latest.owncloud.works/dav/spaces/71135097-2849-442b-b3d8-7701539e8cf5$13e07352-d7e5-42e1-9a4d-2d926dfb4ec7%2113e07352-d7e5-42e1-9a4d-2d926dfb4ec7/.space/readme.md"
        }
      ],
      "webUrl": "https://ocis.ocis-wopi.latest.owncloud.works/f/71135097-2849-442b-b3d8-7701539e8cf5$13e07352-d7e5-42e1-9a4d-2d926dfb4ec7"
    }
  ]
}
```

So that the resolution fails at that point with an internal "unknown drive" error:

```
2023-11-15 00:20:41.879000+0100 ownCloud[36623:6310170] 🛑 | [CONN, Drives] Path for WebDAV endpoint for driveID 71135097-2849-442b-b3d8-7701539e8cf5 could not be generated: unknown drive
```

**Comment by felix-schwarz** [comment]
I've updated the PR for `feature/account-wizard` with the latest SDK which adds support for `<oc:spaceid>`.

**Comment by jesmrec** [comment]
I still get `Resolution Link error` with latest commit.

[ownCloud_15_Nov_2023_at_10_10_00.log.txt](https://github.com/owncloud/ios-app/files/13362525/ownCloud_15_Nov_2023_at_10_10_00.log.txt)

**Comment by michaelstingl** [comment]
@jesmrec please check if it's fixed with the `latest `backend:
- https://owncloud.dev/ocis/deployment/continuous_deployment/

**Comment by jesmrec** [comment]
Problem regarding `spaceid` for `Link resolution error` is fixed as:

ownCloud Web UI 8.0.0-alpha.9 [index.html-qmmJHXdx.mjs:1:453410](https://ocis.ocis-traefik.latest.owncloud.works/js/index.html-qmmJHXdx.mjs)
 Infinite Scale 5.0.0-alpha.2+279d0f856 Community

**Comment by jesmrec** [comment]
### (2)

(maybe expected)

1. Open the app
2. Open Settings view
3. With the app open in Settings view, go to the place in which link will be clicked
4. Click the link and `OPEN ` from the web

Current: `Settings` view on the screen. Clicking on `Done` removes the view and shows the file
Expected: `Settings` view dismissed to show the linked item

https://github.com/owncloud/ios-app/assets/14894746/f6c72f8b-290f-4c47-a5e1-9c9cc0fc6630

iPhoneXR v17.2
`a27068d6`

**Comment by jesmrec** [comment]
### (3)

1. Open a valid link over a cached item
2. Remove device connection
3. Open again the valid link over a cached item

Current: following error is displayed:

<img width="308" alt="Screenshot 2023-11-21 at 17 43 09" src="https://github.com/owncloud/ios-app/assets/14894746/e139adda-a6a2-4ae9-8d0c-affe89d18dae">

device is offline but file is cached. Here a video:

https://github.com/owncloud/ios-app/assets/14894746/496bdcdd-d19f-4680-bad6-bfeed75a5863

iPhoneXR v17.2
`a27068d6`

**Comment by felix-schwarz** [comment]
@jesmrec (2) revealing a private link's location regardless of where in the app a user currently is would take a lot of effort with little to gain. Since it's not expected, I'd leave it as-is for now.

(3) Fixed in [dab3ab4](https://github.com/owncloud/ios-app/pull/1274/commits/dab3ab4958db88182845b16ba6834a8c5b0c7224) in #1274.

**Comment by jesmrec** [comment]
(2) -> won't fox
(3) -> fixed

as today, testing only in instances which returns `spaceid` in a correct way from the `meta` endpoint

From my side, this is healthy and OK to go.
