### ISSUE TITLE
[BUG] Documents non-selectable using Files app integration

### ISSUE THREAD

**Issue by aarononeal** [owncloud/ios-app#747]
### Steps to reproduce
1. Open an app like `iThoughts` or `MindNode`.
2. Enable ownCloud location in Files app pane.
3. Navigate to a folder and create a new document `New Map`.
4. Make a change and close document / return to Files app pane.

### Expected behavior
Document should be selectable and able to be opened again after saving to ownCloud.

### Actual behavior
Document is there, saved, but now grayed out and non-selectable. Some apps, like Pages work, others don't. Nextcloud client works with all.

### Client
**iOS version:**
13.5.1

**ownCloud app version:**
1.3.2 build 158

**Device model:**
iPad Pro

### Server configuration
Bitnami ownCloud under K8S

**Web server:**
Apache

**Database:**
Maria db

**PHP version:**
7.2.31

**ownCloud version:**
10.4.1

**Storage backend (external storage):**
Local Ext4 over CephFS but happens with all storages

**Comment by hosy** [comment]
@aarononeal Thank you for reporting this issue. We will have a look. We already solved some issues with custom mime types for the next release. I will check if this file types will work now.

**Comment by hosy** [comment]
Checked this in MindNode and can confirm the problem. File cannot be opened in MindNode from the DocumentViewController

![image](https://user-images.githubusercontent.com/736109/87596917-3497c100-c6f1-11ea-8223-8ae3f5765956.jpeg)

**Comment by michaelstingl** [comment]
Mime issue again @felix-schwarz ?

**Comment by hosy** [comment]
I tested it with iThoughts and MindNode and can can confirm, that these file types are greyed out.
The given mime-type for these files is `application/octet-stream`. I just added a fix in `OCItem+FileProviderItem.m` for `overriddenUTIBySuffix`
`MindNode` needs `com.mindnode.mindnode.mindmap` as UTI
`iThoughts` needs `com.toketaware.uti.ithoughts.itmz` as UTI

Here we can find maybe some other edge cases, which UTI needs a special conversion: 
https://github.com/IdeasOnCanvas/AppReceiptValidator/blob/master/AppReceiptValidator/AppReceiptValidator%20Tests%20Shared/Test%20Assets/hannes_mac_mindnode_Info.plist
or maybe there:
https://github.com/signalapp/Signal-iOS/blob/master/SignalServiceKit/src/Util/MIMETypeUtil.m

We also have a tester who reported, that PDF files are greyed out. I also added `com.adobe.pdf` for pdf extensions in that place.

**Comment by jesmrec** [comment]
Done! Ready to go in 11.4

**Comment by aarononeal** [comment]
Thanks all! Looking forward to it.

**Comment by michaelstingl** [comment]
Still not fixed @felix-schwarz @hosy : 

![IMG_0107 PNG](https://user-images.githubusercontent.com/214010/91073373-4008d100-e63b-11ea-9368-da973e656cc6.jpeg)

Information about media file:

```
General
ID                                       : 1336003857 (0x4FA1CD11)
Format                                   : Ogg
File size                                : 21.1 MiB
Duration                                 : 5 min 35 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 526 kb/s
recordMyDesktop                          : 0.3.8.1

Video
ID                                       : 2089947090 (0x7C920FD2)
Format                                   : Theora
Duration                                 : 5 min 35 s
Bit rate                                 : 396 kb/s
Width                                    : 1 408 pixels
Height                                   : 1 040 pixels
Display aspect ratio                     : 4:3
Frame rate                               : 15.000 FPS
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.018
Stream size                              : 15.9 MiB (75%)
Writing library                          : Xiph.Org libtheora 1.1 20090822 (Thusnelda)

Audio
ID                                       : 768692105 (0x2DD14F89)
Format                                   : Vorbis
Format settings, Floor                   : 1
Duration                                 : 5 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 100.0 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 16.0 kHz
Compression mode                         : Lossy
Stream size                              : 4.00 MiB (19%)
Writing library                          : libVorbis (Now 100% fewer shells) (20180316 (Now 100% fewer shells))
```


Here you can find the example file:
https://cloud.owncloud.com/index.php/f/5176573

**Comment by jesmrec** [comment]
ogv files were not in the scope of the current one, i guess. We should create an issue or topic (or convert this one) in which every kind of file can be added to UTIs in case it is not recognised by Files App.

**Comment by felix-schwarz** [comment]
@michaelstingl I can't reproduce the issue:

File list | File opened
-------|-----------
![Screen Shot 2020-08-31 at 21 23 18](https://user-images.githubusercontent.com/639669/91758516-706ae500-ebd0-11ea-9856-00f5fda187cd.png) | ![Screen Shot 2020-08-31 at 21 24 31](https://user-images.githubusercontent.com/639669/91758531-75c82f80-ebd0-11ea-844b-b43254e85447.png)

If you can still reproduce the issue, please turn on debug logging and visit the folder in the Files app, then check the log for lines containing the file name, describing the mapping in any of these ways:

```
"Mapped [filename] MIMEType [mimeType] to UTI [uti]"
"Mapped [filename] suffix [file suffix] to UTI [uti]"
"Converted [filename] MIMEType [mimeType] to UTI [uti]"
```

I have (had) VLC installed on that iPhone, which probably registers file type information for ogv files, which could explain why I don't see the issue and you do.

**Comment by michaelstingl** [comment]
Yeah, no VLC on this test device. I’ll test again and post my findings.

**Comment by felix-schwarz** [comment]
I managed to get a dynamically created UTI for `ogv` files from iOS on a freshly set up test device - and it follows the pattern `dyn.[random characters and numbers]`.

I've now modified the File Provider to return the generic type for data when iOS can't convert a MIIME type to a "real" UTI and returns a dynamic UTI  instead, so that files of types not known on the iOS device will no longer appear greyed out in the Files app.

I did not add code to return a "real" UTI for `ogv` files, as I figured that that UTI would still be unknown to iOS and iOS would not be able to make sense of it. After all `org.xiph.ogv` doesn't give away the nature of the file (video).

If VLC is installed, it will register type information for `ogv` files with iOS, providing all the info needed by iOS to classify it as video and convert from MIME Types. Here is its entry in the VLC Info.plist: https://github.com/videolan/vlc-ios/blob/9b136d7534ed4bdf7bcd5ef6cb4f5aa97630396a/Sources/VLC%20for%20iOS-Info.plist#L313

So, if VLC is installed, iOS will return `org.xiph.ogv` for `ogv` files and display the respective files with a  movie icon in the Files app. The fallback to the generic data UTI won't be used in that case.

I think this solution (implemented in 5134a7e1d73e627ba680a07400ca584a7ad60a07) should work best for this and other "unknown" file types.

**Comment by michaelstingl** [comment]
> So, if VLC is installed, iOS will return `org.xiph.ogv` for `ogv` files and display the respective files with a movie icon in the Files app. The fallback to the generic data UTI won't be used in that case.

Sweet solution !! 😍 

@jesmrec @felix-schwarz simple enough for the 11.4.1?

**Comment by felix-schwarz** [comment]
It's implemented already and just needs formal QA testing/verification.

**Comment by jesmrec** [comment]
|| Previous (11.4, `ea77ff3`) | Current `93443c1` |
|:-:|:-:|:-:|
|VLC not installed | ogv file greyed out | ogv file not greyed out<br>ogv file with blank icon  |
|VLC installed | ogv file with movie icon| ogv file with movie icon |

afaik, this is the expected behaviour after the fix. isn't it @felix-schwarz ?

With all the files i have to test, i do not see greyed out files in Files App with commit `93443c1c`

**Comment by felix-schwarz** [comment]
@jesmrec Yeah, that's what it should look like. 🙂

**Comment by jesmrec** [comment]
Then, it's approved on my side

**Comment by jesmrec** [comment]
Ready to 11.4.1
